### ISSUE TITLE
No story found in your file

### ISSUE THREAD

**Issue by vashishthask** [glonlas/AgileStoryPrint#1]
Hi. I tried to use the same excel file which I used in http://www.agilebuddha.com/agile/printing-physical-scrum-board-from-atlassian-jira/ blog. But I get "No story found in your file" message. My excel file has just "Issue Type", "Key", "Summary" and "Story Points" fields.

**Comment by glonlas** [comment]
Hi,

Thank you for your feedback. The tool is in a very early version, I
will improve it. Is it possible to get a sample of your file to try with it?

Have a good day

**Comment by vashishthask** [comment]
https://www.dropbox.com/s/twsx6frduq9vjiq/JIRA.xls?dl=0

**Comment by glonlas** [comment]
Thanks. I will get back to you when the tool will be fixed.

Have a good day

Gérald

2015-03-11 9:28 GMT-04:00 ShriKant Vashishtha <notifications@github.com>:

**Comment by glonlas** [comment]
The file from your dropbox is empty (10kB without any content inside). Or Dropbox may spoil it. 
Do you have another one?

**Comment by vashishthask** [comment]
https://www.dropbox.com/s/h3162wlf5hgqdf9/Jira2.xls?dl=0

**Comment by glonlas** [comment]
Hi @vashishthask 
The bug is fixed, and the patch is online. 
Please tell me if it works well with your files.

Have a good day.

**Comment by vashishthask** [comment]
great. thanks.
