### ISSUE TITLE
http://www.jira2scrumboard.com is down

### ISSUE THREAD

**Issue by lundhgren** [glonlas/AgileStoryPrint#32]
First I would like you for a great service, the best free way to print cards from Jira!

But, the site seems to be down - I can't print cards for the new sprint :'(

**Comment by glonlas** [comment]
Hello lundhgren,

My apologies, I thought I have replied to your message yesterday. Unfortunately, the host, where the website was running, was shut down by my former employer who provided it graciously for the last 2 years. Without funding for this small project, I am looking for an alternative, but I cannot guarantee if the website will be up again. However, you can install it pretty easily if you have a small VM, or a Linux/Unix based OS (work fine on macOS and Linux). Let me know if you need help to install it, I will be happy to improve the documentation.

Thanks

**Comment by lundhgren** [comment]
Ok, I understand. I managed to to get MAMP running and I have installed the packages with "php composer.phar install", but theme.css and compile.js is missing. I suppose it's some bundling issue? Is there another command I should run as well, or is it an environment issue (missing components or similar)?
